saghul/pycares

src/cares.c
tests/tests.py

CPython implementation was interpreting the TTL data as a float, returning invalid data.
CFFI implementation had no problems.
Also improved unit test to verify the types and constraints of the TTL data type

core: CPython implementation TTL parsing issue

---

pycares/_cfficore/__init__.py
src/cares.c
tests/tests.py

Return a the assembled bytes object instead. This also saves a bytes ->
string conversion, which is a good thing.
Fixes: https://github.com/saghul/aiodns/issues/32

core: fix parsing TXT records with invalid UTF-8 chars

---

deps/c-ares/src/ares.h
setup_cares.py

MSYS2 sets up MinGW environment where GCC is used, which is not happy when being fed with VC-style options (/NODEFAULTLIB) and dllimport/dllexport crap

build: fix MinGW build

---

README.rst

It is recommended to use the pycares port for that.

Add FreeBSD building instructions

---

tests/tests.py

It's known to fail, probably due to a misconfigured /etc/hosts

test: skip getaddrinfo6 test on Travis

---

src/pycares/__init__.py
tests/tests.py

Use ffi.gc instead of a dedicated function.

cffi: simplify destroying ares channel

---

setup_cares.py

Unless this was intentional, the Android else branch should handle this case.

Delete the extra add_include_dir linux line

---

src/pycares/__init__.py
tests/tests.py

Reproduce:
#############
import pycares
from tornado.tcpclient import Resolver                
Resolver.configure('tornado.platform.caresresolver.CaresResolver')                                                                        
resolver = Resolver()
resolver.channel = pycares.Channel(sock_state_cb=resolver._sock_state_cb, timeout=1, tries=1,
socket_receive_buffer_size=4096, servers=['127.0.0.1'], tcp_port=5353, udp_port=5353, rotate=False)
##################
Error:    TypeError: initializer for ctype 'char *' must be a cdata pointer, not str

let "pycares" support  ARES_OPT_LOOKUPS option.

---

docs/conf.py

The relative path of _version.py when starting from the docs/ subdirectory is wrong. This fix the '$ make html' build from the docs/ subdirectory.

fix path of _version.py file

---

src/_cffi_src/build_cares.py
src/pycares/__init__.py

Closes #118 
Refactored ffi callbacks to new `extern "Python"` style in order to avoid use of libffi callbacks and W+X mempages usage.

ffi: new style callbacks

---

docs/channel.rst

fix pycares.ares_query_soa_result fileds spelling error

fix spelling errors

---

tests/tests.py

Upgrading c-ares to mitigate vulnerabilities

dependency update to c-ares

---

src/_cffi_src/build_cares.py

Add a flexible member to account for c-ares 1.18 adding an additional
`name` member to `struct ares_addrinfo`.  This fixes the following
exception from cffi, and the resulting test_getaddrinfo* failures:
```pytb
Exception ignored from cffi callback <function _addrinfo_cb at 0x7f5fa890d040>:
Traceback (most recent call last):
File "/tmp/pycares/.tox/py39/lib/python3.9/site-packages/pycares/__init__.py", line 162, in _addrinfo_cb
result = ares_addrinfo_result(res)
File "/tmp/pycares/.tox/py39/lib/python3.9/site-packages/pycares/__init__.py", line 841, in __init__
cname_ptr = ares_addrinfo.cnames
ffi.error: struct ares_addrinfo: wrong total size (cdef says 16, but C compiler says 24). fix it or use "...;" as the last field in the cdef for struct ares_addrinfo to make it flexible
```

core: add flexible member to ares_addrinfo to fix c-ares 1.18

---

.github/workflows/build-wheels.yml
.github/workflows/release-wheels.yml
.github/workflows/test.yml
pyproject.toml
setup.py

This PR enables building of musllinux wheels *and* macOS universal2 wheels which support both x86_64 and the new arm64 platforms
While trying to build the wheels, I've ran into an issue with the legacy setuptools backend so I updated this project to use PEP 517 compatible build system (a matter of adding `pyproject.toml` with `setuptools` specified and some minor changes related to the build isolation).
Additionally I made some changes that were not strictly necessary:
- updated macOS version from 10.15 to 11 as the former is deprecated on GH Actions (https://github.com/actions/virtual-environments/issues/5583)
- updated cibuildwheel version because it seemed like a good idea to bump that though I have not run into any bugs with cibuildwheel 2.0.1
- migrated cibuildwheel configuration …

Build macOS arm64 and musllinux wheels

---

.github/workflows/build-wheels.yml
.github/workflows/release-wheels.yml
.github/workflows/run-cibuildwheel.yml

This PR does 3 things:
- splits out the cibuildwheel run workflow into a separate workflow file that can be called from other workflows (deduplicates the pretty much identical setups in build-wheels.yml and release-wheels.yml)
- cuts the total time of the CI build in half by splitting the Linux run into concurrent jobs:
- manylinux and musllinux x86_64 & i686 (~11 minutes)
- manylinux aarch64 (~26 minutes)
- musllinux aarch64 (~26 minutes)
- bumps cibuildwheel version from 2.8.1 to 2.9.0 to enable Python 3.11 builds with Python 3.11.0rc1 which is guaranteed to be ABI compatible with the final release
I wasn't entirely sure if you'll want the cibuildwheel bump done in this PR along with the changes to how the work is distributed but it's a single line change so it seemed like a reasonable …

Bump cibuildwheel to build for Python 3.11 + CI total time speedups

---

tests/test_all.py

Currently we have multiple test failures with pycares 4.4.0 with c-ares 1.24.  Two of the three are unrelated to the new c-ares version:
For test_query_txt_chunked, the jobscoutdaily.com SPF record changed, so the expected result is wrong.  I think it still has the relevant attributes for the test case.
For test_query_ptr, there's no longer a PTR record at 8.8.8.8, so the test failed with pycares (correctly) reported an error.  It looks like any address with a PTR record will meet the requirements for the test, so I replaced it with the address of one of Google's mail servers.
I'll submit a separate PR for the change related to the newer c-ares.
Scott K

Test data updates to fix test failures

---

tests/test_all.py

See https://github.com/saghul/pycares/issues/193
With this change, all tests pass with c-ares 1.24 (but will fail with 1.18).

Update test_idna_encoding_query_a with new errno to align to new c-ares version

---

deps/build-config/config_android/ares_config.h
deps/build-config/config_cygwin/ares_config.h
deps/build-config/config_darwin/ares_config.h

This PR fix a long standing issue which Android build keep failing due to undefined getservbyport_r in bionic libc.
I think you can close all Android issues for good like #191 since it obviously a user mistake.

Do not define HAVE_GETSERVBYPORT_R for platforms Android, Cygwin, Darwin

---

docs/channel.rst
docs/pycares.rst
setup_cares.py
src/_cffi_src/build_cares.py
src/pycares/__init__.py
tests/test_all.py

The aiodns counter part is https://github.com/aio-libs/aiodns/pull/145
The event thread is now the [recommended way -- see Event Thread example (recommended)](https://c-ares.org/docs.html) to run c-ares (per their docs) as it ensures that if the system configuration changes, c-ares now re-inits the channel automatically.

Add event thread support

---

.github/workflows/build-wheels.yml
.github/workflows/test.yml

In #221 I did a lot of pushes to figure out what had changed between versions. The previous jobs kept running and the CI got tied up.

Cancel previous CI jobs on pull request update

---

.github/workflows/test.yml

Fixes: https://github.com/saghul/pycares/issues/234

Pin Python version to 3.13.3 to avoid Windows build error

---

src/pycares/__init__.py

Making these Final allows a type checker to infer them as `Literal['A']` etc. rather than just `str`.
This can then be used for handling unions of results (e.g. `if result.type == "A": result.host`).

Make result.type Final

---

src/pycares/__init__.py
tests/test_all.py

So recently I actually started to write my own [cython version of this library](https://github.com/Vizonex/cyares) and in doing so I came up with an idea to make it easier to use the socket callbacks.  So instead of users needing to use `ARES_SOCKET_BAD` I made 2 functions that can be used to either process either a read or write file descriptor only. I'll be adding these changes to a future pull request to aiodns since the other reviewers didn't like that I accidently messed around with coverage. (I need to remember to close that [pull request](https://github.com/aio-libs/aiodns/pull/172) and open a new one if these changes get accepted and later updated)
Basically having these should allow users using an event loop to do something like this, this is what I wrote for my version of c-ares …

Add read & write process_fd functions

---

src/pycares/__init__.py

It seems that mypy treats the Final as a "context-sensitive" Literal, which unfortunately doesn't work as a union discriminator, as I previously hoped. It will require an explicit Literal type, which unfortunately introduces a bit of duplication.

Use Literal for type
